parts:
  - title: Prefatory Note
    file : projets/ebabx-2-3/text/0.prefatorynote.md
    template : default
  
  - title: Introduction
    file: projets/ebabx-2-3/text/1.intro-sans-imagenote.md
    template: default
  
  - title: Art in Printing
    file: projets/ebabx-2-3/text/2.artinprinting.md
    template: default
   
  - title: Pictorial Composition
    file: projets/ebabx-2-3/text/3.pictorial.md
    template: default
   
  - title: Type Composition
    file: projets/ebabx-2-3/text/4.type.md
    template: default
   
  - title: Conclusion
    file: projets/ebabx-2-3/text/5.conclusion.md
    template: conclusion
   
  - title: Annexes
    file: projets/ebabx-2-3/text/6.annexes.md
    template: appendices
   
  - title: Entretiens
    file: projets/ebabx-2-3/text/7.entretiens.md
    template: interview
   
  - title: Glossaire
    file: projets/ebabx-2-3/text/8.glossaire.md
    template: references
   
  - title: Références
    file: projets/ebabx-2-3/text/9.references.md
    template: references
   
  - title: Remerciements
    file: projets/ebabx-2-3/text/10.remerciements.md
    template: thanks
